//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace TakeASeatApp.Resources.Account {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class ForgotPassword {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForgotPassword() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("TakeASeatApp.Resources.Account.ForgotPassword", typeof(ForgotPassword).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application failed to send you an automated e-mail with the password reset token:.
        /// </summary>
        public static string Error_EmailNotificationFailed {
            get {
                return ResourceManager.GetString("Error_EmailNotificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in a username or password. The field is required for lookup..
        /// </summary>
        public static string Error_UserNameOrEmailAddressIsRequired {
            get {
                return ResourceManager.GetString("Error_UserNameOrEmailAddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Please disregard this message if you are not aware of a password reset request!.
        /// </summary>
        public static string Message_Email_Notification {
            get {
                return ResourceManager.GetString("Message_Email_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account lookup.
        /// </summary>
        public static string View_AccountLookup {
            get {
                return ResourceManager.GetString("View_AccountLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup account.
        /// </summary>
        public static string View_Button_LookupAccount {
            get {
                return ResourceManager.GetString("View_Button_LookupAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE NOTE: An e-mail message will be sent to the e-mail address associated with the user account. The message will contain a password reset token, along with instructions. The token is only valid for 24 hours. Check the e-mail inbox after lookup..
        /// </summary>
        public static string View_EmailWillBeSend {
            get {
                return ResourceManager.GetString("View_EmailWillBeSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in your account username or the e-mail address associated with your account.
        /// </summary>
        public static string View_PleaseInputUserNameOrEmailAddress {
            get {
                return ResourceManager.GetString("View_PleaseInputUserNameOrEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password forgotten.
        /// </summary>
        public static string View_Title {
            get {
                return ResourceManager.GetString("View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or e-mail address.
        /// </summary>
        public static string View_UserNameOrEmailAddress {
            get {
                return ResourceManager.GetString("View_UserNameOrEmailAddress", resourceCulture);
            }
        }
    }
}
