//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace TakeASeatApp.Resources.Account {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Index {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("TakeASeatApp.Resources.Account.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword_Button_ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword_Button_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string ChangePassword_Label_NewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string ChangePassword_Label_OldPassword {
            get {
                return ResourceManager.GetString("ChangePassword_Label_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ChangePassword_Label_PasswordConfirm {
            get {
                return ResourceManager.GetString("ChangePassword_Label_PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me the new password by e-mail.
        /// </summary>
        public static string ChangePassword_Label_SendReminder {
            get {
                return ResourceManager.GetString("ChangePassword_Label_SendReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string ChangePassword_Legend_ChangePasword {
            get {
                return ResourceManager.GetString("ChangePassword_Legend_ChangePasword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword_View_Title {
            get {
                return ResourceManager.GetString("ChangePassword_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Please use the new password for login from now on; the old password is no longer accepted..
        /// </summary>
        public static string Message_Email_Notification {
            get {
                return ResourceManager.GetString("Message_Email_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change my password.
        /// </summary>
        public static string View_ChangePasword {
            get {
                return ResourceManager.GetString("View_ChangePasword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account.
        /// </summary>
        public static string View_Title {
            get {
                return ResourceManager.GetString("View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occured while the application tried to send you an automated e-mail notification with the new login password:.
        /// </summary>
        public static string Warning_ChangePassword_EmailNotificationFailed {
            get {
                return ResourceManager.GetString("Warning_ChangePassword_EmailNotificationFailed", resourceCulture);
            }
        }
    }
}
